services:
  locentr-db:
    image: postgres:17.6
    container_name: locentr_db
    restart: always
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-locentr_admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-locentr_local_password}
      POSTGRES_DB: ${POSTGRES_DB:-locentr_db}
    volumes:
      - ./postgres:/var/lib/postgresql/data

  locentr-pgadmin:
    image: dpage/pgadmin4
    container_name: locentr_pgadmin
    restart: always
    depends_on:
      - locentr-db
    ports:
      - "${PGADMIN_PORT:-8080}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-change-me-local}
    volumes:
      - ./pgadmin:/var/lib/pgadmin
