"""access list global entries

Revision ID: b9cd0c8a50c3
Revises: 7240d6745044
Create Date: 2026-03-11 13:26:29.693824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b9cd0c8a50c3'
down_revision: Union[str, Sequence[str], None] = '7240d6745044'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_list', sa.Column('company_id', sa.Integer(), nullable=True))
    op.execute(
        """
        UPDATE access_list al
        SET company_id = l.company_id
        FROM location l
        WHERE l.id = al.location_id
          AND al.company_id IS NULL
        """
    )
    op.alter_column('access_list', 'company_id',
               existing_type=sa.Integer(),
               nullable=False)
    op.alter_column('access_list', 'location_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key('fk_access_list_company_id_company', 'access_list', 'company', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM access_list WHERE location_id IS NULL")
    op.drop_constraint('fk_access_list_company_id_company', 'access_list', type_='foreignkey')
    op.alter_column('access_list', 'location_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('access_list', 'company_id')
    # ### end Alembic commands ###